"use strict"

export default {
    "spaces": [{
            "id": 1,
            "title": "Straight Space",
            "image": "vagina.jpg",
            "effect": undefined,
        },
        {
            "id": 2,
            "title": "Straight Space",
            "image": "vagina.jpg",
            "effect": undefined,
        },
        {
            "id": 3,
            "title": "Straight Space",
            "image": "vagina.jpg",
            "effect": undefined,
        },
        {
            "id": 4,
            "title": "Straight Space",
            "image": "vagina.jpg",
            "effect": undefined,
        },
        {
            "id": 5,
            "title": "Straight Space",
            "image": "vagina.jpg",
            "effect": undefined,
        },
        {
            "id": 6,
            "title": "Straight Space",
            "image": "vagina.jpg",
            "effect": undefined,
        },
        {
            "id": 7,
            "title": "Straight Space",
            "image": "vagina.jpg",
            "effect": undefined,
        }, {
            "id": 8,
            "title": "Straight Space",
            "image": "vagina.jpg",
            "effect": undefined,
        }, {
            "id": 9,
            "title": "Straight Space",
            "image": "vagina.jpg",
            "effect": undefined,
        }, {
            "id": 10,
            "title": "Straight Space",
            "image": "vagina.jpg",
            "effect": undefined,
        }, {
            "id": 11,
            "title": "Straight Space",
            "image": "vagina.jpg",
            "effect": undefined,
        },
        {
            "id": 12,
            "title": "Straight Space",
            "image": "vagina.jpg",
            "effect": undefined,
        },
        {
            "id": 13,
            "title": "Straight Space",
            "image": "vagina.jpg",
            "effect": undefined,
        },
        {
            "id": 14,
            "title": "Straight Space",
            "image": "vagina.jpg",
            "effect": undefined,
        },
        {
            "id": 15,
            "title": "Straight Space",
            "image": "vagina.jpg",
            "effect": undefined,
        },
        {
            "id": 16,
            "title": "Straight Space",
            "image": "vagina.jpg",
            "effect": undefined,
        },
        {
            "id": 17,
            "title": "Straight Space",
            "image": "vagina.jpg",
            "effect": undefined,
        }, {
            "id": 18,
            "title": "Straight Space",
            "image": "vagina.jpg",
            "effect": undefined,
        }, {
            "id": 19,
            "title": "Straight Space",
            "image": "vagina.jpg",
            "effect": undefined,
        }, {
            "id": 20,
            "title": "Straight Space",
            "image": "vagina.jpg",
            "effect": undefined,
        },
        {
            "id": 21,
            "title": "Straight Space",
            "image": "vagina.jpg",
            "effect": undefined,
        },
        {
            "id": 22,
            "title": "Straight Space",
            "image": "vagina.jpg",
            "effect": undefined,
        },
        {
            "id": 23,
            "title": "Straight Space",
            "image": "vagina.jpg",
            "effect": undefined,
        },
        {
            "id": 24,
            "title": "Straight Space",
            "image": "vagina.jpg",
            "effect": undefined,
        },
        {
            "id": 25,
            "title": "Straight Space",
            "image": "vagina.jpg",
            "effect": undefined,
        },
        {
            "id": 26,
            "title": "Straight Space",
            "image": "vagina.jpg",
            "effect": undefined,
        },
        {
            "id": 27,
            "title": "Straight Space",
            "image": "vagina.jpg",
            "effect": undefined,
        }, {
            "id": 28,
            "title": "Straight Space",
            "image": "vagina.jpg",
            "effect": undefined,
        }, {
            "id": 29,
            "title": "Straight Space",
            "image": "vagina.jpg",
            "effect": undefined,
        }, {
            "id": 30,
            "title": "Straight Space",
            "image": "vagina.jpg",
            "effect": undefined,
        },
        {
            "id": 31,
            "title": "Straight Space",
            "image": "vagina.jpg",
            "effect": undefined,
        },
        {
            "id": 32,
            "title": "Straight Space",
            "image": "vagina.jpg",
            "effect": undefined,
        },
        {
            "id": 33,
            "title": "Straight Space",
            "image": "vagina.jpg",
            "effect": undefined,
        },
        {
            "id": 34,
            "title": "Straight Space",
            "image": "vagina.jpg",
            "effect": undefined,
        },
        {
            "id": 35,
            "title": "Straight Space",
            "image": "vagina.jpg",
            "effect": undefined,
        },
        {
            "id": 36,
            "title": "Straight Space",
            "image": "vagina.jpg",
            "effect": undefined,
        },
        {
            "id": 37,
            "title": "Straight Space",
            "image": "vagina.jpg",
            "effect": undefined,
        }, {
            "id": 38,
            "title": "Straight Space",
            "image": "vagina.jpg",
            "effect": undefined,
        }, {
            "id": 39,
            "title": "Straight Space",
            "image": "vagina.jpg",
            "effect": undefined,
        }, {
            "id": 40,
            "title": "Straight Space",
            "image": "vagina.jpg",
            "effect": undefined,
        }
    ],
}