const spaces = [
    {
        id: 1,
        title: "Colombian",
        message: "",
        effect: "pot",
    },
    {
        id: 2,
        title: "Flying Too High",
        message: "Lose a turn",
        effect: "loseTurn"
    },
    {
        id: 3,
        title: "Home Grown",
        message: "",
        effect: "pot",
    },
    {
        id: 4,
        title: "Far Out",
        message: "Far Out!",
        effect: "farout",
    },
    {
        id: 5,
        title: "Wacky Weed",
        message: "",            
        effect: "pot",
    },
    {
        id: 6,
        title: "Gainesville Green",
        message: "",            
        effect: "pot",
    },
    {
        id: 7,
        title: "Downtown Pharmacy",
        message: "",            
        effect: "x20",
    }, 
    {
        id: 8,
        title: "Thai Stick",
        message: "",            
        effect: "pot",
    }, 
    {
        id: 9,
        title: "Colombian Red Bud",
        message: "",            
        effect: "pot",
    },
    {
        id: 10,
        title: "Hospital",
        message: "Pay 100x your roll and lose a turn",            
        effect: "hospital",
    }, 
    {
        id: 11,
        title: "Colombian Chiba",
        message: "",            
        effect: "pot",
    }, {
        id: 12,
        title: "You Pay 10x",
        message: "You Pay 10x",            
        effect: "x10",
    },
    {
        id: 13,
        title: "Guerrero Green",
        message: "",            
        effect: "pot",
    },
    {
        id: 14,
        title: "Midnight Airstrip",
        message: "Pay 20x",            
        effect: "x20",
    },
    {
        id: 15,
        title: "Maui Wowie",
        message: "",            
        effect: "pot",
    },
    {
        id: 16,
        title: "Dealing Square",
        message: "",            
        effect: "deal",
    },
    {
        id: 17,
        title: "Sinsemilla",
        message: "",            
        effect: "pot",
    },
    {
        id: 18,
        title: "The Law:",
        message: "Pay 20x",            
        effect: "x20",
    }, 
    {
        id: 19,
        title: "Acapulco Gold",
        message: "",            
        effect: "pot",
    }, 
    {
        id: 20,
        title: "Jackpot",
        message: "You won!",            
        effect: "jackpot",
    }, 
    {
        id: 21,
        title: "Hawaiian",
        message: "",            
        effect: "pot",
    },
    {
        id: 22,
        title: "Vacation Time. Relax.",
        message: "Lose a Turn",            
        effect: "loseTurn",
    },
    {
        id: 23,
        title: "Bum Me Out",
        message: "",            
        effect: "bummer",
    },
    {
        id: 24,
        title: "Nicaraguan",
        message: "",            
        effect: "pot",
    },
    {
        id: 25,
        title: "Munchies!",
        message: "Pay 10x",            
        effect: "x10",
    },
    {
        id: 26,
        title: "Colombian Gold",
        message: "",            
        effect: "pot",
    },
    {
        id: 27,
        title: "Far Out!",
        message: "",            
        effect: "farout",
    },
    {
        id: 28,
        title: "Just Good Pot",
        message: "",            
        effect: "pot",
    }, {
        id: 29,
        title: "Just Bad Pot",
        message: "",            
        effect: "pot",
    }, {
        id: 30,
        title: "Busted...",
        message: "Lose 1 Turn",            
        effect: "loseTurn",
    }, {
        id: 31,
        title: "Vietnamese",
        message: "",            
        effect: "pot",
    },
    {
        id: 32,
        title: "Stickless Thai",
        message: "",            
        effect: "pot",
    },
    {
        id: 33,
        title: "No Tell Car Rental",
        message: "Pay 10x",
        effect: "x10",
    },
    {
        id: 34,
        title: "Panama Red",
        message: "",
        effect: "pot",
    },
    {
        id: 35,
        title: "Mexican",
        message: "",
        effect: "pot",
    },
    {
        id: 36,
        title: "Dealing Square",
        message: "",
        effect: "deal",
    },
    {
        id: 37,
        title: "Jamaican",
        message: "",            
        effect: "pot",
    },
    {
        id: 38,
        title: "Bum Me Out",
        message: "",            
        effect: "bummer",
    }, 
    {
        id: 39,
        title: "Michoacan",
        message: "",            
        effect: "pot",
    }, 
    {
        id: 40,
        title: "Straight Space",
        message: "",            
        effect: "w500",
    }
]

export default spaces